using UnityEngine;

[CreateAssetMenu(fileName = "NewRecipe", menuName = "Inventory/Recipe")]
public class RecipeAsset : ScriptableObject
{
    public Item Soda;//Only one way to make each soda
    public Item[] Ingredients;
    public float SodaPChange;
    public float SodaTChange;
    [Header("Autogenerated. Changing this in the inspector wont do anything")]
    public int RecipeID;
}
